### ISSUE TITLE
Request for the new version of CSR.NINJA

### ISSUE THREAD

**Issue by yutianhot** [udlei/csr.ninja#1]
Thanks

**Comment by yutianhot** [comment]
jQuery.ajaxTransport.send	@	jquery-1.11.1.js:9631
jQuery.extend.ajax	@	jquery-1.11.1.js:9176
jQuery.each.jQuery.(anonymous function)	@	jquery-1.11.1.js:9322
$.validate.submitHandler	@	(index):75
d	@	jquery.validate.min.js:4
(anonymous function)	@	jquery.validate.min.js:4
jQuery.event.dispatch	@	jquery-1.11.1.js:4641
jQuery.event.add.elemData.handle	@	jquery-1.11.1.js:4309

jquery-1.11.1.js:9631 POST http://xxx.com/generate.php 500 (Internal Server Error)

**Comment by udlei** [comment]
Hello, a new version was released.
